version: "3"
services:
  dind:
    build:
        context: .  # ./ubuntu
        dockerfile: ./Dockerfile
        args:
          - USER_ID=${USER_ID}
          - USER_PW=${USER_PW}
    image: dind:1.0
    container_name: docker-in-docker
    ports:
      - "${PORT}:22"  # ssh port
    working_dir: /docker
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./files:/workspace/"
