version: "3"
services:
  dind:
    image: docker.pkg.github.com/tuan-l/dind/dind:1.0
    container_name: docker-in-docker
    ports:
      - "${PORT}:22"  # ssh port
    working_dir: /docker
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./files:/workspace/"
